export const STORIES = [
  { id: "US-01", title: "Calculate a mod from a simple worksheet entry",
    story: "As a premium auditor I want to enter payroll by class and each claim's Actual Losses, the way the experience rating worksheet lists them, and get the Experience Modification.",
    ac: ["Experience Modification = (Actual Primary + Expected Excess) / Expected",
      "Expected Losses = Σ payroll × Expected Loss Rate / 100; per-capita classes are entered in units and not divided (the payroll label switches to units)",
      "Primary Threshold is looked up from total Expected Losses (Table II)",
      "A claim needs only Claim number, Injury type, Open/Closed and Actual Losses; Open/Closed does not affect the result",
      "Actual Primary Losses is read-only and fills in live (about 300 ms after a change) once the form is calculable, otherwise it shows —; a multi-person accident shows its combined capped value on its first row",
      "Sample risks (loss-free, two small claims, one large claim, death claim, per-capita class) load with one click"] },
  { id: "US-02", title: "Primary threshold and claim valuation",
    story: "As a claims analyst I want each claim valued at the risk's primary threshold so the frequency-weighted formula is applied correctly.",
    ac: ["Claims of $250 or less contribute zero", "Actual Losses are capped at the $175,000 Maximum Loss Value", "A claim's primary is capped at threshold − $250"] },
  { id: "US-03", title: "Exception claim types",
    story: "As an analyst I want subrogation, joint-coverage, death, EL+WC, multi-person, contract-medical, non-compensable and COVID claims treated per Sec VI R2.",
    ac: ["Injury type Death uses the $175,000 Average Death Value; Compromised Death or \"S\" Claim asks for Net incurred; Contract Medical asks for the class and is valued at incurred × D-ratio",
      "Subrogation, fraud, joint coverage, non-compensable, EL + WC and multi-person accidents are under a per-claim Special handling disclosure",
      "Subrogation takes $250 off after the net/gross ratio; joint coverage takes it off before", "Multi-person accident primary is capped at 2×PT − $500", "Non-compensable and COVID Cat.12 (12/1/2019–8/31/2024) claims are excluded"] },
  { id: "US-04", title: "Single-claim 25-point cap",
    story: "As an employer with one large claim I want my mod limited to 25 points above my loss-free mod.",
    ac: ["Applies only when exactly one claim has primary losses > 0", "Does not apply when the mod excludes unaudited payroll", "Result shows whether the cap was applied"] },
  { id: "US-05", title: "Eligibility",
    story: "As an insurer I want to know whether the risk qualifies for experience rating.",
    ac: ["Eligible when expected losses ≥ $10,800 (Sept 2025 Plan)", "Below the threshold, eligible only if rated the prior year and the mod exceeds 1.00"] },
  { id: "US-06", title: "Input validation and clear errors",
    story: "As a user I want invalid input rejected with a specific message and no result shown.",
    ac: ["Unknown class code → 422 UNKNOWN_CLASS", "Negative payroll or loss → rejected", "Net incurred must not exceed gross incurred", "Duplicate claim ids rejected", "Claim ids must be non-empty text of at most 100 characters"] },
  { id: "US-07", title: "Result laid out like the experience rating worksheet",
    story: "As a quality analyst I want the result in the worksheet's sections and vocabulary so I can verify it line by line against a ratesheet.",
    ac: ["Heading shows employer, policy, effective and issue dates, and the Primary Threshold",
      "Summary of Payroll and Expected Losses: Class, Payroll, Expected Loss Rate, Expected Losses, D-Ratio, Expected Primary, Expected Excess, with totals",
      "Summary of Claims and Actual Losses: Claim number, Injury type, Open/Closed, Actual Losses, Actual Primary, Actual Excess, with totals and the Plan rule applied",
      "Experience Period Totals, Experience Modification and Loss-Free Rating; Expected Primary + Expected Excess = Expected and Actual Primary + Actual Excess = Actual on every line",
      "A 'How this was calculated' section shows the formula with the numbers substituted"] },
  { id: "US-08", title: "Quality dashboard",
    story: "As a QE lead I want live service stats and the latest automated test results in the app so I can judge release health at a glance.",
    ac: ["Shows requests served, calculations by outcome, approximate p95 latency, mod distribution and uptime from the app's metrics",
      "Refreshes every 5 seconds with a visible last-updated time; auto-refresh can be paused and resumed",
      "Shows Playwright pass/fail counts per project and the failed tests, or a clear empty state when no results exist",
      "Links to Grafana (default http://localhost:3001, configurable)"] },
  { id: "US-09", title: "Experience period and rating effective date",
    story: "As a rating analyst I want the experience period and the rating effective date derived from the policy history so the right experience feeds the mod.",
    ac: ["Experience period is 3 years, from 4 years 9 months to 1 year 9 months before the rating effective date (Sec III R2)",
      "Only completed policies incepting in the period are used; a policy already used in mods for more than 2 years 6 months is excluded; unaudited payroll is excluded and flagged (Sec III R3)",
      "Rating effective date is 12 months after the preceding policy's effective date; a WCIRB-established date governs; a lapse of more than one year resets it (Sec V R1)",
      "Policies of 3 months or less, or that incept and expire between rating effective dates, do not establish a rating effective date (Sec V R1(c))",
      "Every interpretation the Plan does not settle is returned with the result and documented"] },
];
