export const STORIES = [
  { id: "US-01", title: "Calculate a mod from payroll and claims",
    story: "As a premium auditor I want the mod computed from payroll by class and claim losses so I can apply it to a policy.",
    ac: ["Mod = (Actual Primary + Expected Excess) / Expected", "Expected losses = Σ payroll × ELR / 100 (per-capita classes not divided)", "Primary threshold is looked up from total expected losses (Table II)"] },
  { id: "US-02", title: "Primary threshold and claim valuation",
    story: "As a claims analyst I want each claim valued at the risk's primary threshold so the frequency-weighted formula is applied correctly.",
    ac: ["Claims of $250 or less contribute zero", "Actual Losses are capped at the $175,000 Maximum Loss Value", "A claim's primary is capped at threshold − $250"] },
  { id: "US-03", title: "Exception claim types",
    story: "As an analyst I want subrogation, joint-coverage, death, EL+WC, multi-person, contract-medical, non-compensable and COVID claims treated per Sec VI R2.",
    ac: ["Subrogation takes $250 off after the net/gross ratio; joint coverage takes it off before", "Plain death claims use the $175,000 Average Death Value", "Multi-person accident primary is capped at 2×PT − $500", "Non-compensable and COVID Cat.12 (12/1/2019–8/31/2024) claims are excluded"] },
  { id: "US-04", title: "Single-claim 25-point cap",
    story: "As an employer with one large claim I want my mod limited to 25 points above my loss-free mod.",
    ac: ["Applies only when exactly one claim has primary losses > 0", "Does not apply when the mod excludes unaudited payroll", "Result shows whether the cap was applied"] },
  { id: "US-05", title: "Eligibility",
    story: "As an insurer I want to know whether the risk qualifies for experience rating.",
    ac: ["Eligible when expected losses ≥ $10,800 (Sept 2025 Plan)", "Below the threshold, eligible only if rated the prior year and the mod exceeds 1.00"] },
  { id: "US-06", title: "Input validation and clear errors",
    story: "As a user I want invalid input rejected with a specific message and no result shown.",
    ac: ["Unknown class code → 422 UNKNOWN_CLASS", "Negative payroll or loss → rejected", "Net incurred must not exceed gross incurred", "Duplicate claim ids rejected"] },
  { id: "US-07", title: "Transparent breakdown",
    story: "As a quality analyst I want to see how the mod was derived so I can verify it independently.",
    ac: ["Shows E, PT, Ep, Ee, Ap, loss-free mod", "Lists each claim's Actual Losses, Actual Primary and the rule applied"] },
];
